AnyLedger/anyledger-wallet

helpers/rlp_encoder.c

missing header for memcpy function

---

main.c

Name of array is already a pointer

---

main.c

wrong argument order when calling keccak256()

---

transaction.c

Name of array is already pointer to its first element

---

main.c

Function is expecting pointer to variable
I want to resolve #3 

Wrong use of sizeof, size of variable was passed as function argument.

---

main.c

wrong data types for public/private keys

---

.circleci/install_deps.sh
.circleci/run_test.sh
CMakeLists.txt
README.md
cmake/solc.cmake
cmake/wallet.cmake
cmake/zephyr.cmake
crypto/CMakeLists.txt
eth/CMakeLists.txt
helpers/CMakeLists.txt
zephyr/main.c

- makes it possible to crosscompile the target for zephyr
- TODO: use different cflags for zephyr and wallet code

[WIP] Add zephyr build support

---

.gitignore
CMakeLists.txt
cmake/trezor-crypto.cmake
helpers/CMakeLists.txt
thirdparty/trezor-crypto/CMakeLists.txt

- external lib definition for trezor-crypto which we'll most likely use

Add trezor-crypto library

---

helpers/CMakeLists.txt
helpers/macos/endian.h

new pull request with proper github flow

added endian.h shim for macos build

---

cmake/zephyr.cmake
zephyr/config.h
zephyr/main.c
zephyr/upload.c

- a dummy led gpio controller is used for QEMU build

remove `-DQEMU_BUILD`

---

documentation/eclipse-ide.md

Documentation folder and Eclipse IDE tutorial

---

.circleci/images/primary/Dockerfile

I found out that [Dockerfile](https://github.com/AnyLedger/anyledger-wallet/tree/a0a9b98dc3068b20467a98d3f135bd38e03736fb/.circleci/images/primary/Dockerfile) is written with both spaces and tabs for indent.
I would like to edit the file to use only spaces for indent.

Correct indent in Dockerfile

---

eth/web3.c
eth/web3.h
helpers/fp2str.c
helpers/fp2str.h
tests/test_helpers.cpp
zephyr/lwm2m_client.c
zephyr/lwm2m_client.h
zephyr/web3_rpc.c

- added function to convert fixed point integer to a string.
- we'll eventually need a generic algorithm to convert 64/128/256 bit
values
- housekeeping to silence some warnings

add fp2str(uint32_t)

---

tools/pk_gen.py

- correct size of the generated key

Fix: private key generator

---

zephyr/wallet.c
zephyr/wallet.h

- set ETH amount for the transfer
- set global gas price, gas limit values

Wallet updates

---

zephyr/utils.c
zephyr/utils.h
zephyr/wallet.c
zephyr/wallet.h
zephyr/web3_shell.c

- `wallet balance` command
- adds utils to nicely print integers

Display account balance in Ether

---

helpers/math.c
helpers/math.h
helpers/uint256.c
helpers/uint256.h
tests/test_helpers.cpp
zephyr/erc20_shell.c
zephyr/utils.c
zephyr/utils.h

- proper handling of token amounts
- code cleanup

make ERC20 more user friendly

---

BUILD-qemu.md
README.md
examples/tests/src/TestContract.sol
zephyr-wallet/contracts/Token.sol

and fix solidity 0.5 compilation

improving setup documentation

---

CMakeLists.txt
examples/tests/CMakeLists.txt
examples/tests/src/CMakeLists.txt
helpers/CMakeLists.txt

fix helpers path cmake

---

README.md
cmake/nanopb.cmake

Fixes a pesky nanopb error on Ubuntu 18.04

Nanopb uninitialized
